FROM node:20-alpine AS frontend-loader
WORKDIR /app

RUN npm install @hexlet/project-devops-deploy-crud-frontend

FROM python:3.12

COPY --from=caddy:2 /usr/bin/caddy /usr/bin/caddy

RUN apt-get update && apt-get install -y libcap2-bin \
    && setcap -r /usr/bin/caddy \
    && apt-get purge -y libcap2-bin \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY paas/ ./paas/

COPY Caddyfile.production /etc/caddy/Caddyfile

RUN echo '#!/bin/sh\npython -m flask --app paas.scripts.app:app run --host=127.0.0.1 --port=5000 & \ncaddy run --config /etc/caddy/Caddyfile --adapter caddyfile\n' > /app/start.sh && chmod +x /app/start.sh

EXPOSE 8080

CMD ["/app/start.sh"]